Fix compiler errors, MSVC
1. static const my_wc_t some_name = whatever;

As far as compiler is concerned, some_name is not a constant,
and can't be used where constant expression is expected, bringing
error C2099: initializer is not a constant
So, either this needs to be replaced with #defines, in C (
in C++, constexpr would be possible)

2. Fix some truncation bugs.